config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root to: 'pages#home'

  get 'dashboard', to: 'pages#dashboard', as: :dashboard

  resources :plants, only: [:index, :show, :edit, :update]
  resources :pots
  resources :tasks, only: [:update, :destroy]

end

app/models/pot.rb
class Pot < ApplicationRecord
  belongs_to :user
  belongs_to :plant
  has_many :tasks, dependent: :destroy
  mount_uploader :photo, PhotoUploader

  validates :name, presence: true

  def needs?(task_name)
    (Date.today - send("last_#{task_name}")).to_i >= plant.send("#{task_name}_frequency")
  end

  def generate_tasks
    self.incomplete_task("watering")
    self.incomplete_task("potting")
    self.incomplete_task("fertilizing")
    self.incomplete_task("cutting")
  end

  def incomplete_task(task_name)
    return nil unless needs?(task_name)
    task = tasks.find_by(completed: false, name: task_name)
    points = Task::POINTS[task_name]
    task = Task.create(pot: self, name: task_name, points: points) if task.nil?
    return task
  end

  def sum_points
    pot_points = 0
    self.tasks.each do |task|
      pot_points += task.points if task.points && task.completed
    end
    return pot_points
  end

  def count_tasks_by_pot(task_name)
    tasks.where(completed: false).where(name: task_name).size
  end

  def next_task_date(task_name)
   next_task_date = send("last_#{task_name}") + plant.send("#{task_name}_frequency").days
   # if next_task_date < Date.today
   #   next_task_date = Date.today + plant.send("#{task_name}_frequency")
   # end
   return next_task_date
  end

  def late(task_name)
    days_late = (Date.today - next_task_date(task_name)).to_i
  end
end

app/controllers/pots_controller.rb
class PotsController < ApplicationController
  def index
    @pots = policy_scope(Pot)
  end

  def show
    @pot = Pot.find(params[:id])
    @pot.generate_tasks
    authorize(@pot)
  end

  def new
    @pot = Pot.new
    authorize(@pot)
  end

  def create
    @plant = Plant.find(params[:pot][:plant_id])
    @pot = Pot.new(pot_params)
    @pot.user = current_user
    @pot.last_watering = Date.today - 1.day
    @pot.last_cutting = Date.today
    @pot.last_potting = Date.today
    @pot.last_fertilizing = Date.today
    authorize(@pot)
    if @pot.save
      redirect_to pot_path(@pot)
    else
      render :new
    end
  end

  def edit
    @pot = Pot.find(params[:id])
    authorize(@pot)
  end

  def update
    @pot = Pot.find(params[:id])
    @pot.update(pot_params)
    authorize(@pot)
    if @pot.save
      redirect_to pot_path(@pot)
    else
      render :new
    end
  end

  def destroy
    @pot = Pot.find(params[:id])
    @pot.destroy
    @pot.user.points -= 2000
    @pot.user.save
    authorize(@pot)
    redirect_to dashboard_path
  end



  private

  def pot_params
    params.require(:pot).permit(:name, :description, :photo, :size, :adoption_date, :last_watering, :last_potting, :last_fertilizing, :last_cutting, :recipient_size, :plant_id)
  end

end

app/views/pots/_pot_content.html.erb
<div class="pot-content">
  <% pot_picture = pot.photo.url.nil? ? pot.plant.photo : pot.photo %>
  <div class="pot-image"
    style="background-image: url('<%= cl_image_path(pot_picture) %>')">
  </div>
  <div class="pot-info">
    <div class="pot-user-info">
      <div class="header">
        <h3><%= pot.name.capitalize %></h3>
        <%= link_to "Learn more", plant_path(pot.plant), class: "btn btn-minimal "%>
      </div>
      <div class="about_the_pot">
          <p><i><%= pot.description %></i></p>
        </div>
      <div class="border-top">
      </div>
      <div class="recap">
        <div class="recap-item border-right">
          <% unless pot.adoption_date.nil? %>
          <p class="recap-item-p"> You adopted <strong><%= pot.name.capitalize %></strong> on <%= pot.adoption_date.strftime("%B %d, %Y"); %></p>
          <div class="points">
            <%= image_tag "adoption.png", size: 50, class: "icons" %>
          </div>
          <% end %>
        </div>
        <div class="recap-item border-right">
          <p class="recap-item-p"><strong><%= pot.name.capitalize %></strong> belongs to the family of <%= pot.plant.name.capitalize %></p>
          <div class="points">
            <%= image_tag "cactus-family.png", size: 50, class: "icons" %>
          </div>
        </div>
        <div class="recap-item">
          <% if pot.tasks.where(completed: true).count > 0 %>
            <p>You took care of <strong><%= pot.name.capitalize %></strong> <%= pluralize pot.tasks.where(completed: true).count, "time" %> since you met</p>
          <% else %>
          <p>You never took care of <%= pot.name.capitalize %> yet! </p>
          <% end %>
          <div class="points">
            <%= image_tag "care.png",  size: 50, class: "icons" %>
          </div>
        </div>
        <!-- <div class="recap-item">

        </div> -->
      </div>
      <div class="border-top-small">
      </div>
      <%= render "shared/follow_up", pot: pot %>
      <div class="image-links">
        <%#if current_user == pot.user %>
          <%#= link_to pot_path(pot), method: :delete, data: { confirm: "Are you sure?" } do %>
            <!-- <p><%#= pot.name.capitalize %> died ... 👼 </p>
          <%# end %> -->
          <%#= link_to edit_pot_path(pot) do %>
<!--             <i class="fas fa-cog"></i>
 -->          <%# end %>
        <%# end %>
      </div>
    </div>
  </div>
</div>

<!-- <div class="item-border-green">
      <%#= link_to "MY GARDEN", dashboard_path, class: "link-border-green link-flex-end item-border-green" %>
    </div> -->

     <%# unless pot.tasks.empty? %>
        <!-- <div class="pot-statistics">
          <%#= render "shared/follow_up", pot: pot %>
        </div> -->
      <%# end %>

app/views/pots/edit.html.erb
<div class="container", style="margin-bottom: 40px;">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="form-pots">
        <h3>Add your plant !</h3>
        <%= simple_form_for(@pot) do |f| %>
          <div class="form-group">
            <div class="row">
              <div class="col-xs-6">
                <%= f.input :name, placeholder: "Name" %>
              </div>
              <div class="col-xs-6">
                <%= f.association :plant, collection: Plant.all %>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12">
                <%= f.input :description, placeholder: "Type anything you love about this plant!" %>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12">
                <label class="form-control-label string optional" for="pot_photo">Add a photo</label>
                <%= f.input :photo, label: false %>
                <%= f.input :photo_cache, as: :hidden %>
                <img width="100%" class="image-preview">
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12">
              <%= f.input :adoption_date, as: :string, label: "Adoption date", required: false, input_html: {class: "datepicker"}, placeholder: "Since when do you have this plant at home?" %>
              </div>
            </div>
            <label class="form-control-label string optional" for="pot_photo">Select your pot's size</label>
            <div class="flex">
              <%= f.input :recipient_size, :as => :hidden %>
              <div class="select-size" data-size="1"><i class="fa fa-leaf" aria-hidden="true" id="small-leaf"></i> Small</div>
              <div class="select-size" data-size="2"><i class="fa fa-leaf" aria-hidden="true" id="medium-leaf"></i> Medium</div>
              <div class="select-size" data-size="3"><i class="fa fa-leaf" aria-hidden="true" id="large-leaf"></i> Large</div>
            </div>
            <div class="flexbutton">
              <%= f.submit "Save", class: "btn-yellow"  %>
            </div>
            <%#= link_to "Back to my plant", pot_path(@pot), class: "btn-minimal" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/pots/index.html.erb
<div class="container">
  <div class="row">
    <% @pots.each do |pot| %>
      <div class="col-xs-12 col-md-4">
        <%= link_to pot_path(pot) do %>
          <%= render "shared/card", element: pot, select: false %>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= render "shared/footer" %>
</div>

app/views/pots/new.html.erb
<div class="container" style="margin-bottom: 40px;"  >
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="form-pots">
        <h3>Add your plant !</h3>
        <%= simple_form_for(@pot) do |f| %>
          <div class="form-group">
            <div class="row">
              <div class="col-xs-12">
                <%= f.input :name, placeholder: "Name", label: false %>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12">
                <%= f.input :description, placeholder: "Type anything you love about this plant!", label: false,class: "text-resize-none" %>
              </div>
              <div class="row">
                <div class="col-xs-12 plant-upload-image">
                  <label class="form-control-label string optional" for="pot_photo"></label>
                  <%= f.input :photo, label: false, input_html: { style: 'display: none;'} %>
                  <%= f.input :photo_cache, as: :hidden %>
                  <a href="#" class="btn btn-minimal" id="upload-fake-btn"> <i class= "mdi mdi-arrow-up-bold-circle-outline"></i> Add a photo</a>
                  <img width="100%" class="image-preview">
                </div>
              </div>
              <div class="row">
                <div class="col-xs-12 plant-choice-image">
                  <div id="div_plant_name" data-toggle="modal" data-target="#myModal">
                    <i class="mdi mdi-cursor-default-outline"></i> Add your plant's family
                  </div>
                </div>
              </div>
              <div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog modal-lg" role="document">
                  <div class="modal-content">
                    <div class="modal-body">
                      <h3>Find your plant's family!</h3>
                      <div class="row">
                        <% Plant.all.each do |plant| %>
                          <div class="col-xs-12 col-md-4">
                            <%= f.radio_button(:plant_id, plant.id, class: "hidden") %>
                            <%= f.label("plant_id_#{plant.id}") do %>
                              <%= render "shared/card", element: plant, select: true %>
                            <% end %>
                          </div>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12">
              <%= f.input :adoption_date, as: :string, label: "Adoption date", required: false, input_html: {class: "datepicker"}, placeholder: "Since when do you have this plant at home?", label: false %>
              </div>
            </div>
            <label class="form-control-label string optional" for="pot_photo">Select your pot's size</label>
            <div class="flex">
              <%= f.input :recipient_size, :as => :hidden %>
              <div class="select-size" data-size="1"><i class="fa fa-leaf" aria-hidden="true" id="small-leaf"></i> Small</div>
              <div class="select-size" data-size="2"><i class="fa fa-leaf" aria-hidden="true" id="medium-leaf"></i> Medium</div>
              <div class="select-size" data-size="3"><i class="fa fa-leaf" aria-hidden="true" id="large-leaf"></i> Large</div>
            </div>
            <div class="flexbutton">
              <%= f.submit "Save", class: "btn-yellow"  %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/pots/show.html.erb
<div class="container container-gray container-show" id="container-pot-show">
  <%= render "pot_content", pot: @pot %>
</div>