config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root to: 'pages#home'

  get 'dashboard', to: 'pages#dashboard', as: :dashboard

  resources :plants, only: [:index, :show, :edit, :update]
  resources :pots
  resources :tasks, only: [:update, :destroy]

end

app/views/pages/_dashboard-container.html.erb
  <div class="dashboard-container">
    <div class="top-dashboard">
      <div class="left-side-dashboard">
        <div class="welcome-heading">
          <h3 class="welcome-title">Welcome <%= user.status %> !</h3>
          <div class="player-badges">
            <div class="status-message">
              <% if user.is_master %>
                You have become a real master on taking care of plants. Stay tuned for upcoming rewards!
              <% else %>
                You are <span class="no-padding-left status-points"><%= user.left_for_next_status %> points</span>  away from <%= user.next_status %>
             <% end %>
           </div>
           <div class="player-bages-dashboard">
            <div class="player-stats">
              <!-- <div class="points-circle"> -->
                <div class="points">
                  <%= image_tag("points_icon.png", size: 40) %>
                </div>
                <span class="counter_points"><%= user.points %></span><span  class="points-element"><%= "point".pluralize(user.points) %></span>
              <!-- </div> -->
            </div>
            <div class="player-stats">
              <!-- <div class="points-circle"> -->
                <div class="points">
                  <%= image_tag("plants.png", height: 40) %>
                </div>
                <span class="counter_points"><%= user.pots.size %></span>
                <span class="points-element"><%= "plant".pluralize(user.pots.size) %></span>
              <!-- </div> -->
            </div>
            <div class="player-stats">
              <!-- <div class="points-circle"> -->
                <div class="points">
                  <%= image_tag("cactus-family.png", height: 40) %>
                </div>
                <span class="counter_points"><%= user.tasks.where(completed: true).size %></span>
                <span class="points-element"><%= "action".pluralize(user.tasks) %></span>
              <!-- </div> -->
            </div>
           </div>
          </div>
        </div>
  <!--       <div class="col-xs-12 col-md-6">
  -->   <div class="user-tasks inner-padding">
          <div class="top-tasks">
            <div class="user-task-title">
              <h3>My tasks</h3>
              <% if current_user.tasks.where(completed: false).size > 0 %>
                <p>You have <span id="counter_tasks" class="no-padding-left"><strong><%= current_user.tasks.where(completed: false).size %></strong></span> <span class="no-padding-left"><%= "task".pluralize %></span> to perform today </p>
              <% else %>
                <p>Well done!! Enjoy your day!</p>
              <% end %>
            </div>
            <div class="tasks-badges">
              <div class="tasks-badges-test">
                <%=  image_tag "watering.png", size: 40, class: "icons" %>
              </div>
              <div class="tasks-badges-test">
                <%=  image_tag "fertilize.jpg", size: 40, class: "icons" %>
              </div>
              <div class="tasks-badges-test">
                <%=  image_tag "plants.png", size: 40, class: "icons" %>
              </div>
              <div class="tasks-badges-test">
                <%=  image_tag "potting.jpg", size: 40, class: "icons" %>
              </div>
            </div>

          </div>
          <div class="task-list">

            <% if current_user.tasks.where(completed: false).size > 0 %>
              <% Task::TASKS.each do |task_name| %>
              <!-- <div class="col-xs-12 col-md-6"> -->
                <% if current_user.tasks.where(completed: false, name: task_name).size > 0  %>
                  <div class="task-title-card">
                    <span class="task-title-badge">
                      <span class="span-paytone"><%= task_name.upcase %></span>
                      <div class="task-badge">
                        <%= render "shared/badge", task_name: task_name %>
                      </div>
                    </span>
                    <div class="task-title">
                      <%= render "shared/task_type", tasks: Task.includes(:pot).where(name: task_name, completed: false, pot: current_user.pots), task_name: task_name %>
                    </div>
                  </div>
                <% end %>
              <!-- </div> -->
              <% end %>
            <% else %>
              <div class="image-height-300">
                <img src="https://cdn.dribbble.com/users/729829/screenshots/2547652/galshir-cacti.gif" alt="" >
                 <div class="white-square">
                </div>
              </div>

            <% end %>

          </div>

        </div>
      </div>
      <div class="user-ranking">
        <h3>🏆 HIGHEST SCORES 🏆</h3>
        <div class="user-gained-points">
          <!-- points, plants, actions -->
        </div>
        <div class="ranking-table">
          <%= render "shared/ranking" %>
        </div>
      </div>
    </div>

    <div class="user-garden">
      <div class="user-garden-header">
        <h3>My greenhouse</h3>
        <div class="item-border-green">
          <%= link_to "+ ADD A PLANT", new_pot_path, class: "link-border-green" %>
        </div>
      </div>
      <div class="row">
        <% pots.each do |pot|%>
          <div class="col-xs-12 col-sm-4 col-md-3">
            <%= link_to pot_path(pot) do %>
              <%= render "shared/card", element: pot, select: false %>
            <% end %>
          </div>
        <% end %>
      </div>

    </div>
  </div>

app/views/pages/dashboard.html.erb
<div class="container container-gray full-screen">
  <div id="dashboard-content" class="wrapper-dashboard">
   <%= render "dashboard-container", user: @user, pots: @pots %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/pages/home.html.erb
<div class="container container-gray">
  <div class="banner">
    <div class="big-header">
      <h1>NEVER SAY GOODBYE TO YOUR PLANTS AGAIN</h1>
    </div>
    <div class="home-image">
      <%= image_tag "potify_cover.png" %>
    </div>
    <%= link_to "Start now", dashboard_path, class: "btn-yellow grow" %>
  </div>
  <div class="presentation">
    <h2>PAMPER YOUR PLANTS !</h2>
    <p class="source-font">With Potify, caring for your plants becomes fun !</p>
    <div class="key-learning">
      <div class="reminder">
        <%= image_tag("cactus-family.png", height: 60) %>
        Never forget to take care of your plants
      </div>
      <div class="reminder">
        <%= image_tag("adoption.png", height: 50) %>
        Need more information? We got it covered
      </div>
      <div class="reminder">
        <%= image_tag("points_icon.png", height: 50) %>
        Earn points when you complete your tasks
      </div>
    </div>
  </div>
  <div class="cards-content">
    <div class="home-card-header">
      <h2>OUR HAPPIEST POTS</h2>
      <p class="source-font">Their masters know how to please them !</p>
    </div>

    <%= render "shared/home_cards", elements: @best_users %>

  </div>
  <!-- <div class="cards-content">
    <h2>CURIOUS ABOUT PLANTS?</h2>
    <p class="source-font">Find out more about indoor plants and find your next baby pot! </p>
    <%#= render "shared/home_cards", elements: @plants %>
    <%#= link_to "DISCOVER", plants_path, class: "navbar-potify-link btn btn-minimal in-banner" %>
  </div> -->

</div>

<%= render "shared/footer" %>