config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root to: 'pages#home'

  get 'dashboard', to: 'pages#dashboard', as: :dashboard

  resources :plants, only: [:index, :show, :edit, :update]
  resources :pots
  resources :tasks, only: [:update, :destroy]

end

app/models/plant.rb
class Plant < ApplicationRecord
  has_many :pots, dependent: :nullify

  include PgSearch
  pg_search_scope :search_by_name_and_category,
    against: [ :name, :category ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController

  def index
    if params[:query].present?
      @plants = policy_scope(Plant).order(created_at: :desc).where("name ILIKE ?", "%#{params[:query]}%")
    else
      @plants = policy_scope(Plant).order(created_at: :desc)
    end
  end

  def show
    @plant = Plant.find(params[:id])
    authorize(@plant)
  end

  def edit
    @plant = Plant.find(params[:id])
    authorize(@plant)
  end

  def update
    @plant = Plant.find(params[:id])
    @plant.update(plant_params)
    authorize(@plant)
    redirect_to plant_path(@plant)
  end

  private

  def plant_params
    params.require(:plant).permit(:category, :description, :watering_frequency, :watering_quantity, :potting_frequency, :fertilizing_quantity, :fertilizing_frequency, :fertilizing_type, :exposition, :cutting_frequency, :temperature)
  end



end

app/views/plants/edit.html.erb
<div class="container" style="margin-bottom: 40px;"  >
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="form-pots">
        <h3>Edit your plant !</h3>
        <%= simple_form_for(@plant) do |f| %>
          <div class="form-group">
            <div class="row">
              <div class="col-xs-12">
                <%= f.input :name, placeholder: "Name" %>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12">
              <%= f.input :category, as: :string, label: "Category", required: false%>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12">
                <%= f.input :description, placeholder: "Type anything you love about this plant!", class: "text-resize-none" %>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12">
              <%= f.input :watering_frequency, as: :integer, label: "watering_frequency", required: false %>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12">
              <%= f.input :watering_quantity, as: :integer, label: "watering_quantity", required: false %>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12">
              <%= f.input :potting_frequency, as: :integer, label: "potting_frequency", required: false %>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12">
              <%= f.input :fertilizing_quantity, as: :integer, label: "fertilizing_quantity", required: false %>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12">
              <%= f.input :fertilizing_frequency, as: :integer, label: "fertilizing_frequency", required: false %>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12">
              <%= f.input :fertilizing_type, as: :string, label: "fertilizing_type", required: false %>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12">
              <%= f.input :exposition, as: :integer, label: "exposition", required: false %>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12">
              <%= f.input :cutting_frequency, as: :integer, label: "cutting_frequency", required: false %>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12">
              <%= f.input :temperature, as: :integer, label: "temperature", required: false %>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12">
              <%= f.input :plant_url, as: :string, label: "plant_url", required: false %>
              </div>
            </div>


            <div class="flexbutton">
              <%= f.submit "Save", class: "btn-yellow"  %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/plants/index.html.erb
<div class="container container-gray full-screen">
  <div class="container">
    <h1 style="text-align: center;
      margin: 50px;">Looking for a plant?</h1>
    <%= render "shared/search" %>
    <div class="row">
      <% @plants.each do |plant| %>
        <div class="col-xs-12 col-md-4">
          <%= link_to plant_path(plant) do %>
            <%= render "shared/card", element: plant, select: false %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/plants/show.html.erb
<div class="container container-gray container-show">
  <div class="pot-content">
    <% if current_user.admin == true %>
      <%= link_to "update", edit_plant_path(@plant) %>
    <% end %>
    <div class="plant-image" style="background-image: url('<%= @plant.photo %>')">
    </div>
    <div class="pot-info">
      <div class="header">
        <h3><%= @plant.name %></h3>
      </div>
      <div class="border-top">
      </div>
      <p class="about_the_plant">About this plant: <%= @plant.description %></p>
      <div class="border-top-small">
      </div>
      <%= render "shared/plant_information", plant: @plant %>
    </div>
  </div>
</div>
<%= render "shared/footer" %>